# Generated by Django 5.0.3 on 2024-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='ordinal',
            field=models.IntegerField(default=0),
        ),
    ]
